title: Valores Globales
menu:
  img: /u/base/logo.svg
  items:
  - label: Inicio
    url: /
  - label: Caracter√≠sticas
    url: /#caracteristicas
  - label: Tratamientos
    url: /#tratamientos
  - label: Opiniones
    url: /#opiniones
  - label: Contacto
    url: /#contacto
    btn: cta
footer:
  dots:
  - url: https://www.facebook.com/takamakanaturalbeauty/
  - url: https://www.instagram.com/takamaka_belleza_natural/
  - url: https://g.page/takamakanaturalbeauty
    icon: location_on
  - url: https://g.page/r/CYuSOAZCKGDcEBM
    icon: add_location
