title: Valores Globales
menu:
  image: base/logo.svg
  items:
  - label: Inicio
    link: /
  - label: Caracter√≠sticas
    link: /#caracteristicas
  - label: Tratamientos
    link: /#tratamientos
  - label: Opiniones
    link: /#opiniones
  - label: Contacto
    link: /#contacto
    button: cta
footer:
  dots:
  - link: https://www.facebook.com/takamakanaturalbeauty/
  - link: https://www.instagram.com/takamaka_belleza_natural/
  - link: https://g.page/takamakanaturalbeauty
    icon: location_on
  - link: https://g.page/r/CYuSOAZCKGDcEBM
    icon: add_location
